[tool.poetry]
name = "data-structure-and-algorithm"
version = "0.1.0"
description = ""
authors = ["Sid Hayoun Lee <sidhlee@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pytest-watch = "^4.2.0"

[tool.poetry.dev-dependencies]
mypy = "^0.931"
pytest = "^6.2.5"
flake8 = "^4.0.1"
black = "^22.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
